name: Release Charts

on:
  push:
    branches:
      - ciy-release*

jobs:
  release:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to gitlab hub
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com/ronen48/ciy
          username: ronen
          password: glpat-MUekjoxQDubT9QoHyuEx

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.gitlab.com/ronen48/ciy/ciy-descheduler:latest
            registry.gitlab.com/ronen48/ciy/ciy-descheduler:1.0.0
          no-cache: true
